# Application Config
spring.application.name=shipment-early-warning

# Server
server.port=8080

# SQLite DataSource
spring.datasource.url=jdbc:sqlite:shipment_db.sqlite
spring.datasource.driver-class-name=org.sqlite.JDBC

# JPA / Hibernate
spring.jpa.database-platform=org.hibernate.community.dialect.SQLiteDialect
spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=false

# Python AI Microservice
ai.service.url=http://localhost:8000

# External API Keys
news.api.key=074862dd4df14d4a8c69aa849984448b
weather.api.key=51b9bcaaa98a4d96a13145318261103
ors.api.key=eyJvcmciOiI1YjNjZTM1OTc4NTExMTAwMDFjZjYyNDgiLCJpZCI6ImNjMGE0ZmRmYmI5ZTRmMTQ5ZjQ4MGY4ZmY3MDg2Y2QzIiwiaCI6Im11cm11cjY0In0=

# CORS
spring.mvc.cors.allowed-origins=http://localhost:5173
